@startuml

class Solution42{
    +main(String args[])

}

class parseCSV{
    -List<> temp = new ArrayList<>
    +readCSV(String input.txt)
    +organizeData()
    +exportData(String output.txt)
}

Solution42 --o parseCSV

@enduml