@startuml

Class Solution41{
    +main(args: String[])
    'NameSorter sort = new NameSorter()
    'sort.readNames("input.txt")
    'sort.sortNames()
    'sort.exportNames("output.txt")
}

Class NameSorter{
    -ArrayList<String> names;
    'read names into an array list
    +readNames(String input)
    'take in the array list to sort
    'return sorted names
    +sortNames()
    'export all sorted names to an output file
    +exportNames(String output)

    'for testing purposes; changing arraylist names
    +nameList(List<String> name)
    'for testing purposes; returning the arrayList names
    +getList()
}

Solution41 --o NameSorter
@enduml